version: '3.9'
services:
  postgres:
    container_name: nestjs-auth
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  postgres-test:
    container_name: nestjs-auth-test
    image: postgres:latest
    ports:
      - 5434:5432
    volumes:
      - testdb:/data/postgres:/data/postgres-test
    env_file:
      - docker.env.test
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: nestjs-auth-pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - pgadmin:/data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  db:
  testdb:
  pgadmin: